// File generated by FlutterFire CLI.
// This file should be replaced with the actual firebase_options.dart
// generated by running: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Replace these with your actual Firebase project configuration.
/// Run `flutterfire configure` to generate this file automatically.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web; // Use web config for macOS
      case TargetPlatform.windows:
        return web; // Use web config for Windows
      case TargetPlatform.linux:
        return web; // Use web config for Linux
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase Web Configuration
  // Project: sagovlaws
  // https://console.firebase.google.com/project/sagovlaws
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi2JL9S7D-bQ00ZwiercOpfTSDczJ9ZJI',
    appId: '1:1063086634234:web:d9e5539350769e9f5f8543',
    messagingSenderId: '1063086634234',
    projectId: 'sagovlaws',
    authDomain: 'sagovlaws.firebaseapp.com',
    storageBucket: 'sagovlaws.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi2JL9S7D-bQ00ZwiercOpfTSDczJ9ZJI',
    appId: '1:1063086634234:android:d9e5539350769e9f5f8543',
    messagingSenderId: '1063086634234',
    projectId: 'sagovlaws',
    storageBucket: 'sagovlaws.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi2JL9S7D-bQ00ZwiercOpfTSDczJ9ZJI',
    appId: '1:1063086634234:ios:d9e5539350769e9f5f8543',
    messagingSenderId: '1063086634234',
    projectId: 'sagovlaws',
    storageBucket: 'sagovlaws.firebasestorage.app',
    iosBundleId: 'com.example.rasidUqn',
  );
}
